// 500개 명언 데이터베이스 (quotes.js)
const QUOTES_500 = [
    { id: 1, quote: "시작하는 방법은 말하는 것을 멈추고 행동하기 시작하는 것이다.", author: "월트 디즈니", category: "실행" },
    { id: 2, quote: "오늘 할 수 있는 일을 내일로 미루지 마라.", author: "벤자민 프랭클린", category: "습관" },
    { id: 3, quote: "성공은 최종적인 것이 아니며, 실패는 치명적인 것이 아니다. 중요한 것은 계속할 수 있는 용기다.", author: "윈스턴 처칠", category: "용기" },
    { id: 4, quote: "당신이 할 수 있다고 믿든 할 수 없다고 믿든, 당신이 옳다.", author: "헨리 포드", category: "마인드" },
    { id: 5, quote: "나는 결코 실패하지 않는다. 나는 단지 작동하지 않는 10,000가지 방법을 찾았을 뿐이다.", author: "토마스 에디슨", category: "끈기" },
    { id: 6, quote: "길을 찾거나, 아니면 만들어라.", author: "한니발", category: "도전" },
    { id: 7, quote: "바람이 불지 않을 때 바람개비를 돌리는 방법은 앞으로 달려가는 것이다.", author: "데일 카네기", category: "동기부여" },
    { id: 8, quote: "가장 어두운 밤도 언젠가는 끝나고 해는 다시 떠오른다.", author: "빅토르 위고", category: "희망" },
    { id: 9, quote: "어제보다 나은 오늘의 내가 되는 것이 진정한 고귀함이다.", author: "어니스트 헤밍웨이", category: "성장" },
    { id: 10, quote: "우리가 반복적으로 하는 행동이 바로 우리 자신이다. 그러므로 탁월함은 행동이 아니라 습관이다.", author: "아리스토텔레스", category: "습관" },
    { id: 11, quote: "단순함이 궁극의 정교함이다.", author: "레오나르도 다빈치", category: "지혜" },
    { id: 12, quote: "혁신은 리더와 추종자를 구분하는 잣대다.", author: "스티브 잡스", category: "비즈니스" },
    { id: 13, quote: "준비에 실패하는 것은 실패를 준비하는 것이다.", author: "벤자민 프랭클린", category: "준비" },
    { id: 14, quote: "문제를 복잡하게 만드는 것은 쉽지만, 단순하게 만드는 것은 예술이다.", author: "에드워드 데 보노", category: "단순화" },
    { id: 15, quote: "인생은 자신을 찾는 것이 아니라 자신을 만드는 과정이다.", author: "조지 버나드 쇼", category: "인생" },
    { id: 16, quote: "기회는 일어나는 것이 아니라 당신이 만드는 것이다.", author: "크리스 그로서", category: "기회" },
    { id: 17, quote: "배움을 멈추는 사람은 20살이든 80살이든 늙은 사람이다.", author: "헨리 포드", category: "성장" },
    { id: 18, quote: "최고의 복수는 엄청난 성공이다.", author: "프랭크 시나트라", category: "동기부여" },
    { id: 19, quote: "행동은 모든 성공의 기본 열쇠다.", author: "파블로 피카소", category: "실행" },
    { id: 20, quote: "꿈을 이루고자 하는 용기만 있다면 모든 꿈은 실현될 수 있다.", author: "월트 디즈니", category: "꿈" },
    { id: 21, quote: "성공의 비결은 평범한 일을 비범하게 잘 해내는 것이다.", author: "존 D. 록펠러", category: "성공" },
    { id: 22, quote: "나무를 심기에 가장 좋은 시기는 20년 전이었다. 두 번째로 좋은 시기는 바로 지금이다.", author: "중국 속담", category: "타이밍" },
    { id: 23, quote: "질문하지 않는 자는 배울 수 없다.", author: "소크라테스", category: "배움" },
    { id: 24, quote: "남을 알고 자신을 알면 백 번 싸워도 위태롭지 않다.", author: "손자", category: "전략" },
    { id: 25, quote: "승리하는 자는 결코 포기하지 않고, 포기하는 자는 결코 승리하지 못한다.", author: "나폴레온 힐", category: "끈기" },
    { id: 26, quote: "행복은 목적지가 아니라 여행하는 방식이다.", author: "로이 M. 굿맨", category: "행복" },
    { id: 27, quote: "세상을 바꾸고 싶다면 먼저 자신부터 바꾸어라.", author: "마하트마 간디", category: "변화" },
    { id: 28, quote: "실수를 해보지 않은 사람은 한 번도 새로운 것을 시도해보지 않은 사람이다.", author: "알베르트 아인슈타인", category: "도전" },
    { id: 29, quote: "속도를 줄이고 인생을 즐겨라. 너무 빨리 가면 경치뿐만 아니라 어디로 가는지도 놓친다.", author: "에디 캔터", category: "휴식" },
    { id: 30, quote: "만족을 아는 사람은 영원히 부족함이 없다.", author: "노자", category: "마인드" },
    { id: 31, quote: "미래를 예측하는 가장 좋은 방법은 미래를 창조하는 것이다.", author: "피터 드러커", category: "비즈니스" },
    { id: 32, quote: "위대한 일을 해내는 유일한 방법은 당신이 하는 일을 사랑하는 것이다.", author: "스티브 잡스", category: "열정" },
    { id: 33, quote: "지식에 투자하는 것이 항상 최고의 이자를 낸다.", author: "벤자민 프랭클린", category: "투자" },
    { id: 34, quote: "고통이 지나간 자리에는 성장이 남는다.", author: "괴테", category: "성장" },
    { id: 35, quote: "산을 움직이려 하는 자는 작은 돌을 들어내는 일부터 시작한다.", author: "공자", category: "실행" },
    { id: 36, quote: "태도는 사소한 것이지만 엄청난 차이를 만든다.", author: "윈스턴 처칠", category: "태도" },
    { id: 37, quote: "생각하는 대로 살지 않으면 사는 대로 생각하게 된다.", author: "폴 부르제", category: "마인드" },
    { id: 38, quote: "한 번 포기하면 그것이 습관이 된다. 절대 포기하지 마라.", author: "마이클 조던", category: "끈기" },
    { id: 39, quote: "자신감은 성공의 첫 번째 비결이다.", author: "랄프 왈도 에머슨", category: "자신감" },
    { id: 40, quote: "계획 없는 목표는 단지 소망에 불과하다.", author: "앙투안 드 생텍쥐페리", category: "계획" },
    { id: 41, quote: "비관론자는 모든 기회에서 어려움을 보고, 낙관론자는 모든 어려움에서 기회를 본다.", author: "윈스턴 처칠", category: "관점" },
    { id: 42, quote: "우리는 우리가 상상하는 것보다 훨씬 더 강하다.", author: "헬렌 켈러", category: "용기" },
    { id: 43, quote: "작은 일에 충실한 자는 큰 일에도 충실하다.", author: "성경", category: "성실" },
    { id: 44, quote: "무례함은 강한 체하는 약자의 모방이다.", author: "에릭 호퍼", category: "인간관계" },
    { id: 45, quote: "인내는 쓰지만 그 열매는 달다.", author: "장 자크 루소", category: "인내" },
    { id: 46, quote: "탁월함은 재능이 아니라 훈련된 습관이다.", author: "아리스토텔레스", category: "역량" },
    { id: 47, quote: "지혜로운 자는 남의 잘못을 보고 자신의 잘못을 고친다.", author: "푸블릴리우스 시루스", category: "지혜" },
    { id: 48, quote: "기다리는 자에게 좋은 일이 생기지만, 서두르는 자에게는 더 나은 일이 생긴다.", author: "에이브러햄 링컨", category: "적극성" },
    { id: 49, quote: "모든 성취의 시작점은 갈망이다.", author: "나폴레온 힐", category: "열정" },
    { id: 50, quote: "성공이란 열정을 잃지 않고 실패에서 실패로 걸어가는 능력이다.", author: "윈스턴 처칠", category: "회복탄력성" },
    { id: 51, quote: "말하기 전에 생각하고, 생각하기 전에 읽어라.", author: "프란 레보위츠", category: "독서" },
    { id: 52, quote: "내일을 여는 유일한 한계는 오늘에 대한 우리의 의심이다.", author: "프랭클린 D. 루스벨트", category: "믿음" },
    { id: 53, quote: "불가능해 보이는 것도 누군가가 해내기 전까지는 불가능한 것이다.", author: "넬슨 만델라", category: "도전" },
    { id: 54, quote: "진정한 위험은 아무것도 하지 않는 것이다.", author: "데니스 웨이틀리", category: "도전" },
    { id: 55, quote: "행운은 준비가 기회를 만났을 때 발생한다.", author: "세네카", category: "준비" },
    { id: 56, quote: "작은 구멍 하나가 큰 배를 가라앉힌다.", author: "벤자민 프랭클린", category: "신중함" },
    { id: 57, quote: "오늘의 규율이 내일의 자유를 낳는다.", author: "조코 윌링크", category: "자기관리" },
    { id: 58, quote: "용기란 두려움이 없는 것이 아니라, 두려움보다 더 중요한 것이 있다고 판단하는 것이다.", author: "앰브로즈 레드문", category: "용기" },
    { id: 59, quote: "책 없는 방은 영혼 없는 육체와 같다.", author: "키케로", category: "독서" },
    { id: 60, quote: "가장 훌륭한 리더는 부하들이 '우리가 해냈다'고 말하게 만드는 리더다.", author: "노자", category: "리더십" },
    { id: 61, quote: "성공은 매일 반복되는 작은 노력들의 합이다.", author: "로버트 콜리어", category: "꾸준함" },
    { id: 62, quote: "스스로를 신뢰하라. 그러면 어떻게 살아야 할지 알게 될 것이다.", author: "괴테", category: "자신감" },
    { id: 63, quote: "경험은 혹독한 스승이다. 시험을 먼저 치르고 가르침은 나중에 주기 때문이다.", author: "버넌 로", category: "경험" },
    { id: 64, quote: "지식보다 중요한 것은 상상력이다.", author: "알베르트 아인슈타인", category: "창의성" },
    { id: 65, quote: "다른 사람의 좋은 점을 찾는 것은 당신 자신의 좋은 점을 발견하는 길이다.", author: "아놀드 H. 글래소우", category: "인간관계" },
    { id: 66, quote: "바쁜 것만으로는 충분하지 않다. 개미들도 바쁘다. 중요한 것은 무엇 때문에 바쁜가이다.", author: "헨리 데이비드 소로", category: "우선순위" },
    { id: 67, quote: "바람의 방향을 바꿀 수는 없지만, 돛을 조정해 목적지에 도달할 수는 있다.", author: "지미 딘", category: "유연성" },
    { id: 68, quote: "시간은 가장 가치 있는 자원이다.", author: "테오프라스토스", category: "시간" },
    { id: 69, quote: "화가 날 때는 열까지 세고, 아주 심할 때는 백까지 세어라.", author: "토머스 제퍼슨", category: "감정조절" },
    { id: 70, quote: "당신이 남긴 평판은 당신이 방을 나간 뒤 사람들이 하는 말이다.", author: "제프 베이조스", category: "브랜딩" },
    { id: 71, quote: "시도조차 하지 않는 것보다는 실패하는 것이 훨씬 낫다.", author: "테어도어 루스벨트", category: "도전" },
    { id: 72, quote: "비교는 기쁨을 훔쳐가는 도둑이다.", author: "시어도어 루스벨트", category: "행복" },
    { id: 73, quote: "침묵은 때로 가장 강력한 대답이다.", author: "달라이 라마", category: "지혜" },
    { id: 74, quote: "모든 사람에게 친구인 사람은 누구에게도 친구가 아니다.", author: "아리스토텔레스", category: "인간관계" },
    { id: 75, quote: "끝까지 해내는 사람만이 시작의 의미를 안다.", author: "괴테", category: "완성" },
    { id: 76, quote: "겸손은 모든 미덕의 기초다.", author: "공자", category: "인성" },
    { id: 77, quote: "변화를 두려워하지 않는 자만이 발전할 수 있다.", author: "빌 게이츠", category: "변화" },
    { id: 78, quote: "위대한 성과는 작은 조각들이 모여 완성된다.", author: "빈센트 반 고흐", category: "꾸준함" },
    { id: 79, quote: "과거를 지배하는 자가 미래를 지배한다.", author: "조지 오웰", category: "역사" },
    { id: 80, quote: "친절은 귀머거리도 들을 수 있고 눈먼 자도 볼 수 있는 언어다.", author: "마크 트웨인", category: "친절" },
    { id: 81, quote: "자신의 능력을 과소평가하지 마라. 한계는 생각 속에만 존재한다.", author: "존 우든", category: "잠재력" },
    { id: 82, quote: "사람을 얻는 가장 확실한 방법은 그들의 이익을 먼저 생각하는 것이다.", author: "카네기", category: "비즈니스" },
    { id: 83, quote: "결과는 과정의 정직함을 배신하지 않는다.", author: "이창호", category: "노력" },
    { id: 84, quote: "우리는 우리가 믿는 만큼만 볼 수 있다.", author: "질베르트 세스브롱", category: "시각" },
    { id: 85, quote: "인생의 가장 큰 영광은 넘어지지 않는 것이 아니라, 넘어질 때마다 일어서는 데 있다.", author: "넬슨 만델라", category: "재도약" },
    { id: 86, quote: "가장 중요한 일을 가장 덜 중요한 일의 자비에 맡기지 마라.", author: "괴테", category: "집중" },
    { id: 87, quote: "자신의 한계를 인정할 때 비로소 그 한계를 넘어설 수 있다.", author: "알베르트 아인슈타인", category: "자기인식" },
    { id: 88, quote: "적을 없애는 가장 좋은 방법은 그를 친구로 만드는 것이다.", author: "에이브러햄 링컨", category: "인간관계" },
    { id: 89, quote: "생각을 바꾸면 세상이 바뀐다.", author: "노먼 빈센트 필", category: "긍정" },
    { id: 90, quote: "질문은 지혜의 등불이다.", author: "아랍 속담", category: "탐구" },
    { id: 91, quote: "최고의 마케팅은 훌륭한 제품이다.", author: "필립 코틀러", category: "비즈니스" },
    { id: 92, quote: "오늘 흘린 땀은 내일의 보상이 된다.", author: "마르쿠스 아우렐리우스", category: "성실" },
    { id: 93, quote: "지나간 일에 연연하지 말고, 다가올 일에 대비하라.", author: "체스터필드", category: "현재집중" },
    { id: 94, quote: "가장 큰 실수는 아무런 실수도 하지 않으려고 하는 것이다.", author: "엘버트 허버드", category: "실행" },
    { id: 95, quote: "약속을 지키는 것은 신뢰를 쌓는 가장 빠른 길이다.", author: "워렌 버핏", category: "신뢰" },
    { id: 96, quote: "행동 없는 비전은 백일몽이고, 비전 없는 행동은 악몽이다.", author: "일본 속담", category: "비전" },
    { id: 97, quote: "칭찬은 고래도 춤추게 한다.", author: "켄 블랜차드", category: "동기부여" },
    { id: 98, quote: "바다의 깊이는 잴 수 있어도 사람의 마음은 잴 수 없다.", author: "명심보감", category: "통찰" },
    { id: 99, quote: "우리가 가진 유일한 한계는 우리가 스스로 정한 한계뿐이다.", author: "나폴레온 힐", category: "잠재력" },
    { id: 100, quote: "지금 시작하라. 내일은 시작하기에 항상 늦다.", author: "에드워드 영", category: "실행" },
    { id: 101, quote: "배우기만 하고 생각하지 않으면 어둡고, 생각하기만 하고 배우지 않으면 위태롭다.", author: "공자", category: "배움" },
    { id: 102, quote: "모든 벽은 문이다.", author: "랄프 왈도 에머슨", category: "희망" },
    { id: 103, quote: "시간을 지배하는 자가 인생을 지배한다.", author: "알랭", category: "시간" },
    { id: 104, quote: "성공의 80%는 일단 출석하는 것이다.", author: "우디 앨런", category: "성실" },
    { id: 105, quote: "작은 성공들을 축하하라. 그것들이 모여 큰 성취가 된다.", author: "존 C. 맥스웰", category: "성장" },
    { id: 106, quote: "말보다 행동이 더 크게 울린다.", author: "영국 속담", category: "실행" },
    { id: 107, quote: "가장 위대한 승리는 자기 자신을 이기는 것이다.", author: "플라톤", category: "자기관리" },
    { id: 108, quote: "지혜는 학교에서 배우는 것이 아니라 평생을 통해 얻는 것이다.", author: "알베르트 아인슈타인", category: "지혜" },
    { id: 109, quote: "위험을 감수하지 않는 것이 인생에서 가장 큰 위험이다.", author: "오프라 윈프리", category: "도전" },
    { id: 110, quote: "뿌리가 튼튼해야 바람에 흔들리지 않는다.", author: "용비어천가", category: "기본" },
    { id: 111, quote: "기회는 꼬리가 없어서 지나가면 잡을 수 없다.", author: "그리스 속담", category: "타이밍" },
    { id: 112, quote: "용기는 두려움을 느끼면서도 한 걸음 내딛는 것이다.", author: "존 웨인", category: "용기" },
    { id: 113, quote: "자기 자신을 사랑하는 것이 평생의 로맨스의 시작이다.", author: "오스카 와일드", category: "자존감" },
    { id: 114, quote: "남의 시선에 갇혀 살지 마라.", author: "스티브 잡스", category: "주체성" },
    { id: 115, quote: "성공을 확신하는 것이 성공의 첫 걸음이다.", author: "보브", category: "자신감" },
    { id: 116, quote: "진정한 친구는 온 세상이 떠날 때 찾아오는 사람이다.", author: "월터 윈첼", category: "인간관계" },
    { id: 117, quote: "문제가 있다는 것은 당신이 여전히 살아있다는 증거다.", author: "노먼 빈센트 필", category: "긍정" },
    { id: 118, quote: "매일 조금씩 나아지는 것만큼 확실한 성공은 없다.", author: "카이젠 철학", category: "습관" },
    { id: 119, quote: "기쁨을 나누면 두 배가 되고, 슬픔을 나누면 반이 된다.", author: "스웨덴 속담", category: "공감" },
    { id: 120, quote: "생각을 심으면 행동을 거두고, 행동을 심으면 습관을 거둔다.", author: "새뮤얼 스마일스", category: "습관" },
    { id: 121, quote: "어떤 결정을 내리지 않는 것도 하나의 결정이다.", author: "하비 콕스", category: "의사결정" },
    { id: 122, quote: "당신이 걸어온 길이 당신이 누구인지를 말해준다.", author: "세네카", category: "인생" },
    { id: 123, quote: "작은 일에 성실하지 못한 사람은 큰 일에도 실패한다.", author: "하워드 슐츠", category: "성실" },
    { id: 124, quote: "폭풍우는 영원히 지속되지 않는다.", author: "로버트 H. 슐러", category: "위로" },
    { id: 125, quote: "경쟁자를 이기려 하지 말고 어제의 자신을 이겨라.", author: "마이클 펠프스", category: "성장" },
    { id: 126, quote: "지식을 얻으려면 공부를 해야 하고, 지혜를 얻으려면 관찰을 해야 한다.", author: "마릴린 보스 사반트", category: "통찰" },
    { id: 127, quote: "성공은 준비된 자에게 찾아온다.", author: "루이 파스퇴르", category: "준비" },
    { id: 128, quote: "완벽함보다 완료함이 낫다.", author: "셰릴 샌드버그", category: "실행" },
    { id: 129, quote: "침묵은 거짓말을 하지 않는다.", author: "키에르케고르", category: "진실" },
    { id: 130, quote: "희망은 깨어있는 자의 꿈이다.", author: "아리스토텔레스", category: "희망" },
    { id: 131, quote: "탁월한 리더는 사람들의 잠재력을 끌어낸다.", author: "잭 웰치", category: "리더십" },
    { id: 132, quote: "정직은 최고의 정책이다.", author: "벤자민 프랭클린", category: "정직" },
    { id: 133, quote: "한 걸음 늦게 가는 것이 돌아가는 것보다 빠르다.", author: "한국 속담", category: "신중함" },
    { id: 134, quote: "남을 비판하기 전에 자신의 신발부터 닦아라.", author: "영국 속담", category: "겸손" },
    { id: 135, quote: "노력은 결코 배신하지 않는다.", author: "이승엽", category: "노력" },
    { id: 136, quote: "가장 큰 모험은 당신이 꿈꾸는 삶을 살아가는 것이다.", author: "오프라 윈프리", category: "꿈" },
    { id: 137, quote: "배우기를 멈추면 늙기 시작한다.", author: "헨리 포드", category: "배움" },
    { id: 138, quote: "비바람을 두려워하지 않는 나무가 깊은 뿌리를 내린다.", author: "장자", category: "성장" },
    { id: 139, quote: "성공은 실패를 거듭하면서도 열정을 잃지 않는 것이다.", author: "윈스턴 처칠", category: "열정" },
    { id: 140, quote: "작은 친절이 세상을 따뜻하게 만든다.", author: "이솝", category: "친절" },
    { id: 141, quote: "불평하는 사람은 해결책을 찾지 못한다.", author: "데일 카네기", category: "태도" },
    { id: 142, quote: "행동이 없는 지식은 열매 없는 나무와 같다.", author: "탈무드", category: "실행" },
    { id: 143, quote: "말이 씨가 된다.", author: "한국 속담", category: "언어" },
    { id: 144, quote: "위대한 생각은 마음에서 나온다.", author: "보브나르그", category: "마음" },
    { id: 145, quote: "시간은 모든 것을 해결해 주는 훌륭한 의사다.", author: "메난드로스", category: "시간" },
    { id: 146, quote: "당신의 태도가 당신의 고도를 결정한다.", author: "지그 지글러", category: "태도" },
    { id: 147, quote: "모든 성취는 결심에서 출발한다.", author: "존 F. 케네디", category: "결단" },
    { id: 148, quote: "지나간 일에 눈물 흘리지 말고 미소 지어라.", author: "닥터 수스", category: "긍정" },
    { id: 149, quote: "아침의 1시간은 저녁의 3시간과 같다.", author: "독일 속담", category: "시간관리" },
    { id: 150, quote: "어제의 나보다 1%만 더 성장하라.", author: "제임스 클리어", category: "습관" },
    { id: 151, quote: "남을 부러워하는 순간 불행이 시작된다.", author: "쇼펜하우어", category: "마인드" },
    { id: 152, quote: "자신의 가치를 인정하지 않으면 남들도 인정해주지 않는다.", author: "체스터필드", category: "자존감" },
    { id: 153, quote: "성공은 하루아침에 이루어지지 않는다.", author: "로마 속담", category: "인내" },
    { id: 154, quote: "비우지 않으면 새로운 것을 채울 수 없다.", author: "법정 스님", category: "비움" },
    { id: 155, quote: "진정한 부자는 가진 것이 많은 사람이 아니라 부족함이 없는 사람이다.", author: "에피쿠로스", category: "지혜" },
    { id: 156, quote: "남의 말을 경청하는 것이 대화의 절반이다.", author: "제노", category: "경청" },
    { id: 157, quote: "시작이 반이다.", author: "아리스토텔레스", category: "실행" },
    { id: 158, quote: "스스로 길을 여는 자에게 세상은 길을 내어준다.", author: "랄프 왈도 에머슨", category: "주체성" },
    { id: 159, quote: "역경은 사람을 부유하게 하지는 않으나 지혜롭게 만든다.", author: "풀러", category: "역경" },
    { id: 160, quote: "행복은 감사의 문으로 들어와 불평의 문으로 나간다.", author: "무명", category: "감사" },
    { id: 161, quote: "꿈을 날짜와 함께 적어두면 그것은 목표가 된다.", author: "그렉 S. 레이드", category: "목표" },
    { id: 162, quote: "물방울이 바위를 뚫는다.", author: "오비디우스", category: "끈기" },
    { id: 163, quote: "당신의 오늘은 어제 생각한 결과다.", author: "부처", category: "생각" },
    { id: 164, quote: "도전 없는 인생은 무의미하다.", author: "헬렌 켈러", category: "도전" },
    { id: 165, quote: "배움에는 왕도가 없다.", author: "유클리드", category: "배움" },
    { id: 166, quote: "자신을 알라.", author: "소크라테스", category: "자기인식" },
    { id: 167, quote: "지혜로운 자는 말을 아낀다.", author: "성경", category: "언어" },
    { id: 168, quote: "진정한 승자는 패배를 두려워하지 않는 자다.", author: "빌리 진 킹", category: "용기" },
    { id: 169, quote: "모든 순간은 새로운 시작이다.", author: "T.S. 엘리엇", category: "시작" },
    { id: 170, quote: "열정 없는 재능은 연료 없는 엔진이다.", author: "무명", category: "열정" },
    { id: 171, quote: "남에게 대접받고자 하는 대로 남을 대접하라.", author: "황금률", category: "인간관계" },
    { id: 172, quote: "가장 훌륭한 지혜는 친절이다.", author: "탈무드", category: "친절" },
    { id: 173, quote: "변화는 고통스럽지만 성장을 위해 필수적이다.", author: "C.S. 루이스", category: "변화" },
    { id: 174, quote: "행운의 여신은 용감한 자의 편이다.", author: "베르길리우스", category: "용기" },
    { id: 175, quote: "남을 지배하는 자는 힘이 있는 자지만, 자신을 지배하는 자는 진정으로 강한 자다.", author: "노자", category: "자기통제" },
    { id: 176, quote: "인생은 속도가 아니라 방향이다.", author: "괴테", category: "방향성" },
    { id: 177, quote: "어떤 일도 완벽하게 준비될 때까지 기다리지 마라.", author: "조지 패튼", category: "결단" },
    { id: 178, quote: "마음의 평화가 최고의 행복이다.", author: "달라이 라마", category: "평화" },
    { id: 179, quote: "당신이 세상에서 보고 싶은 변화가 되어라.", author: "마하트마 간디", category: "실행" },
    { id: 180, quote: "성실함이 없는 재능은 쓸모가 없다.", author: "키케로", category: "성실" },
    { id: 181, quote: "고난은 사람의 진가를 시험하는 리트머스 시험지다.", author: "셰익스피어", category: "시련" },
    { id: 182, quote: "우리는 우리가 상상한 대로 자라난다.", author: "요한 볼프강 폰 괴테", category: "비전" },
    { id: 183, quote: "말하기 전에 두 번 생각하고, 글 쓰기 전에 세 번 생각하라.", author: "도쿠가와 이에야스", category: "신중함" },
    { id: 184, quote: "끝이 좋으면 모든 것이 좋다.", author: "셰익스피어", category: "완성" },
    { id: 185, quote: "지나간 고통은 아름다운 추억이 된다.", author: "키케로", category: "위로" },
    { id: 186, quote: "남의 결점을 찾지 말고 자신의 장점을 키워라.", author: "데일 카네기", category: "성장" },
    { id: 187, quote: "시간은 금이다.", author: "벤자민 프랭클린", category: "시간" },
    { id: 188, quote: "생각을 넓히면 시야가 넓어진다.", author: "공자", category: "통찰" },
    { id: 189, quote: "작은 구멍이 배를 침몰시킨다.", author: "영국 속담", category: "위험관리" },
    { id: 190, quote: "용기 있는 자만이 자유를 얻는다.", author: "페리클레스", category: "자유" },
    { id: 191, quote: "정직한 자의 발걸음은 굳건하다.", author: "솔로몬", category: "정직" },
    { id: 192, quote: "자신을 낮추면 남이 나를 높여준다.", author: "채근담", category: "겸손" },
    { id: 193, quote: "모든 것은 마음먹기에 달렸다.", author: "원효대사", category: "마인드" },
    { id: 194, quote: "희망을 잃지 않는 한 실패는 없다.", author: "안창호", category: "희망" },
    { id: 195, quote: "오늘의 배움이 내일의 힘이다.", author: "세종대왕", category: "배움" },
    { id: 196, quote: "뿌린 대로 거두리라.", author: "갈라디아서", category: "인과" },
    { id: 197, quote: "행동이 없는 말은 공허하다.", author: "칸트", category: "실행" },
    { id: 198, quote: "지혜로운 자는 침묵 속에서 답을 찾는다.", author: "피타고라스", category: "지혜" },
    { id: 199, quote: "포기하지 않는 마음이 가장 큰 무기다.", author: "이순신", category: "끈기" },
    { id: 200, quote: "인생 최고의 승리는 자신과의 싸움에서 이기는 것이다.", author: "플라톤", category: "자기극복" },
    { id: 201, quote: "오늘의 고난은 내일의 영광을 위한 밑거름이다.", author: "키케로", category: "희망" },
    { id: 202, quote: "작은 일에 정성을 다하는 것이 위대함의 시작이다.", author: "중용", category: "정성" },
    { id: 203, quote: "남을 이기는 자는 힘이 세지만, 자신을 이기는 자는 진정 강하다.", author: "노자", category: "자제력" },
    { id: 204, quote: "모든 큰 나무도 한 알의 작은 씨앗에서 시작되었다.", author: "도덕경", category: "시작" },
    { id: 205, quote: "가장 훌륭한 대화는 잘 듣는 것이다.", author: "플루타르코스", category: "경청" },
    { id: 206, quote: "눈앞의 이익보다 먼 미래의 신뢰를 선택하라.", author: "상도 철학", category: "신뢰" },
    { id: 207, quote: "겸손함은 배움의 첫 번째 관문이다.", author: "소크라테스", category: "겸손" },
    { id: 208, quote: "어려움 속에는 반드시 기회가 숨어 있다.", author: "알베르트 아인슈타인", category: "기회" },
    { id: 209, quote: "내일의 성공은 오늘 무엇을 준비하느냐에 달렸다.", author: "몰리에르", category: "준비" },
    { id: 210, quote: "웃음은 두 사람 사이의 가장 가까운 거리다.", author: "빅토르 보르게", category: "인간관계" },
    { id: 211, quote: "마음이 흐리면 세상이 흐려 보인다.", author: "원효", category: "마음" },
    { id: 212, quote: "시간을 아끼는 것이 생명을 아끼는 것이다.", author: "루쉰", category: "시간" },
    { id: 213, quote: "지혜는 경험의 딸이다.", author: "레오나르도 다빈치", category: "경험" },
    { id: 214, quote: "아무리 느려도 멈추지 않으면 반드시 도착한다.", author: "공자", category: "꾸준함" },
    { id: 215, quote: "자신의 약점을 아는 것이 강함의 시작이다.", author: "헤겔", category: "자기인식" },
    { id: 216, quote: "좋은 습관은 훌륭한 운명을 만든다.", author: "드라이든", category: "습관" },
    { id: 217, quote: "분노는 남을 태우기 전에 나를 먼저 태운다.", author: "부처", category: "감정조절" },
    { id: 218, quote: "새로운 길을 가려면 낡은 지도를 버려라.", author: "미셸 푸코", category: "혁신" },
    { id: 219, quote: "모든 시작은 어렵지만 포기하지 않는 자가 열매를 맺는다.", author: "독일 격언", category: "인내" },
    { id: 220, quote: "진정한 용기는 혼자서라도 옳은 길을 가는 것이다.", author: "마크 트웨인", category: "용기" },
    { id: 221, quote: "남의 성공을 질투하지 말고 그의 노력을 배워라.", author: "괴테", category: "성장" },
    { id: 222, quote: "비밀을 지키는 것은 지혜의 척도다.", author: "솔로몬", category: "신중함" },
    { id: 223, quote: "생각을 많이 할수록 행동은 명확해진다.", author: "데카르트", category: "사고" },
    { id: 224, quote: "신뢰는 거울과 같아서 한 번 깨지면 다시 붙이기 어렵다.", author: "쇼펜하우어", category: "신뢰" },
    { id: 225, quote: "오늘 흘린 땀방울이 내일의 열매가 된다.", author: "탈무드", category: "노력" },
    { id: 226, quote: "과거에 얽매이면 미래를 바라볼 수 없다.", author: "버트런드 러셀", category: "미래" },
    { id: 227, quote: "책은 마음의 양식이요, 지혜의 샘이다.", author: "키케로", category: "독서" },
    { id: 228, quote: "어두움을 탓하기보다 작은 촛불 하나를 켜라.", author: "공자", category: "실행" },
    { id: 229, quote: "바른 마음에서 바른 행동이 나온다.", author: "율곡 이이", category: "기본" },
    { id: 230, quote: "기회는 준비된 사람의 손을 잡는다.", author: "파스퇴르", category: "기회" },
    { id: 231, quote: "지나친 욕심은 가진 것마저 잃게 만든다.", author: "이솝", category: "절제" },
    { id: 232, quote: "배움에는 끝이 없다.", author: "순자", category: "배움" },
    { id: 233, quote: "칭찬은 사람의 잠재력을 깨우는 마법이다.", author: "카네기", category: "동기부여" },
    { id: 234, quote: "진정한 부는 마음의 평화에 있다.", author: "세네카", category: "평화" },
    { id: 235, quote: "실패를 두려워하면 결코 성공의 문을 열 수 없다.", author: "베이브 루스", category: "도전" },
    { id: 236, quote: "언행일치는 신뢰의 기본이다.", author: "도산 안창호", category: "정직" },
    { id: 237, quote: "친구를 얻는 가장 좋은 방법은 스스로 친구가 되어주는 것이다.", author: "에머슨", category: "인간관계" },
    { id: 238, quote: "가장 높은 곳에 오르려면 가장 낮은 곳부터 시작하라.", author: "푸블릴리우스 시루스", category: "겸손" },
    { id: 239, quote: "지혜로운 자는 흐르는 물처럼 유연하다.", author: "노자", category: "유연성" },
    { id: 240, quote: "모든 성취는 작은 행동의 누적이다.", author: "제임스 클리어", category: "습관" },
    { id: 241, quote: "정직한 고난은 거짓된 영광보다 값지다.", author: "톨스토이", category: "정직" },
    { id: 242, quote: "마음의 문은 안에서만 열린다.", author: "헤겔", category: "마음" },
    { id: 243, quote: "자기 자신을 믿는 것이 모든 기적의 시작이다.", author: "로망 롤랑", category: "자신감" },
    { id: 244, quote: "남의 잘못을 용서하는 것이 진정한 승리다.", author: "간디", category: "용서" },
    { id: 245, quote: "하루를 충실히 보낸 자는 밤에 편안히 잠든다.", author: "레오나르도 다빈치", category: "성실" },
    { id: 246, quote: "비전을 품은 자는 결코 길을 잃지 않는다.", author: "토인비", category: "비전" },
    { id: 247, quote: "진정한 리더십은 섬김에서 나온다.", author: "그린리프", category: "리더십" },
    { id: 248, quote: "작은 절제가 큰 자유를 가져다준다.", author: "에픽테토스", category: "자기관리" },
    { id: 249, quote: "미래는 꿈의 아름다움을 믿는 자들의 것이다.", author: "엘리너 루스벨트", category: "꿈" },
    { id: 250, quote: "오늘이라는 날은 다시 오지 않는다.", author: "단테", category: "시간" },
    { id: 251, quote: "용서는 최고의 복수다.", author: "스페인 속담", category: "인간관계" },
    { id: 252, quote: "행동 없는 믿음은 죽은 것이다.", author: "성경", category: "실행" },
    { id: 253, quote: "작은 친절이 큰 기적을 만든다.", author: "마더 테레사", category: "친절" },
    { id: 254, quote: "지혜는 고통을 통해 완성된다.", author: "아이스킬로스", category: "지혜" },
    { id: 255, quote: "진정한 친구는 한 영혼이 두 몸에 사는 것이다.", author: "아리스토텔레스", category: "우정" },
    { id: 256, quote: "시간이 없다는 것은 핑계에 불과하다.", author: "에디슨", category: "시간관리" },
    { id: 257, quote: "남을 비추는 등불이 되면 내 앞길도 밝아진다.", author: "불경", category: "나눔" },
    { id: 258, quote: "열정이 없는 삶은 식어버린 재와 같다.", author: "바이런", category: "열정" },
    { id: 259, quote: "자신을 이기는 자가 가장 강한 자다.", author: "노자", category: "자기극복" },
    { id: 260, quote: "지식은 나누어야 커진다.", author: "베이컨", category: "나눔" },
    { id: 261, quote: "모든 시련은 성장의 디딤돌이다.", author: "헬렌 켈러", category: "시련" },
    { id: 262, quote: "말에 무게를 두면 신뢰가 따른다.", author: "명심보감", category: "언어" },
    { id: 263, quote: "오늘의 선택이 내일의 운명을 만든다.", author: "사르트르", category: "선택" },
    { id: 264, quote: "겸손한 자는 넘어지지 않는다.", author: "탈무드", category: "겸손" },
    { id: 265, quote: "평범함 속에 비범함이 숨어 있다.", author: "파스칼", category: "통찰" },
    { id: 266, quote: "마음의 평정은 그 어떤 보물보다 귀하다.", author: "마르쿠스 아우렐리우스", category: "평화" },
    { id: 267, quote: "스스로를 돕는 자를 하늘이 돕는다.", author: "새뮤얼 스마일스", category: "자립" },
    { id: 268, quote: "노력하지 않고 얻은 것은 쉽게 사라진다.", author: "소포클레스", category: "노력" },
    { id: 269, quote: "지혜로운 자는 과거를 돌아보며 미래를 준비한다.", author: "투키디데스", category: "역사" },
    { id: 270, quote: "웃음은 영혼의 청량제다.", author: "조지 허버트", category: "긍정" },
    { id: 271, quote: "약속은 빚과 같다.", author: "독일 속담", category: "신뢰" },
    { id: 272, quote: "작은 일에 감사하는 마음이 행복의 열쇠다.", author: "에피쿠로스", category: "감사" },
    { id: 273, quote: "자신을 속이지 않는 것이 정직의 시작이다.", author: "율곡", category: "정직" },
    { id: 274, quote: "생각을 바꾸면 행동이 바뀌고, 행동이 바뀌면 인생이 바뀐다.", author: "윌리엄 제임스", category: "변화" },
    { id: 275, quote: "어둠이 깊을수록 새벽은 가깝다.", author: "토머스 풀러", category: "희망" },
    { id: 276, quote: "우리는 생각하는 대로 존재한다.", author: "데카르트", category: "철학" },
    { id: 277, quote: "진정한 힘은 부드러움에서 나온다.", author: "노자", category: "유연성" },
    { id: 278, quote: "남의 떡을 탐내면 내 손의 떡을 잃는다.", author: "한국 속담", category: "절제" },
    { id: 279, quote: "배우는 사람은 언제나 젊다.", author: "아이스킬로스", category: "성장" },
    { id: 280, quote: "용기는 공포를 극복하는 과정이다.", author: "마크 트웨인", category: "용기" },
    { id: 281, quote: "작은 실천이 백 마디 말보다 낫다.", author: "괴테", category: "실행" },
    { id: 282, quote: "오늘의 고통은 지나가고 영광만 남는다.", author: "세네카", category: "위로" },
    { id: 283, quote: "신뢰는 돈으로 살 수 없다.", author: "버핏", category: "신뢰" },
    { id: 284, quote: "스스로를 낮추는 자는 높아지리라.", author: "성경", category: "겸손" },
    { id: 285, quote: "마음이 바르면 세상이 바르게 보인다.", author: "퇴계 이황", category: "인성" },
    { id: 286, quote: "지나간 시간에 연연하지 마라.", author: "스토아 학파", category: "현재" },
    { id: 287, quote: "친절한 말은 짧고 쉽지만 울림은 끝이 없다.", author: "마더 테레사", category: "친절" },
    { id: 288, quote: "시련은 강한 자를 단련시킨다.", author: "니체", category: "성장" },
    { id: 289, quote: "모든 인간은 배움을 갈망한다.", author: "아리스토텔레스", category: "배움" },
    { id: 290, quote: "남을 이해하는 것이 지혜의 시작이다.", author: "스피노자", category: "이해" },
    { id: 291, quote: "절망 속에서도 희망을 찾는 것이 인간이다.", author: "빅터 프랭클", category: "희망" },
    { id: 292, quote: "인내는 쓰지만 그 결과는 매우 달콤하다.", author: "루소", category: "인내" },
    { id: 293, quote: "작은 노력이 모여 큰 바위를 움직인다.", author: "동양 격언", category: "노력" },
    { id: 294, quote: "자기 자신을 정복하는 자가 온 세상을 얻는다.", author: "부처", category: "자제" },
    { id: 295, quote: "시간은 한 번 지나가면 다시 오지 않는다.", author: "호라티우스", category: "시간" },
    { id: 296, quote: "진정한 명예는 바른 행동에서 온다.", author: "키케로", category: "명예" },
    { id: 297, quote: "친구의 결점을 덮어주는 것이 참된 우정이다.", author: "플루타르코스", category: "우정" },
    { id: 298, quote: "행복은 가진 것에 감사할 때 찾아온다.", author: "탈무드", category: "감사" },
    { id: 299, quote: "지혜로운 리더는 귀를 열고 입을 닫는다.", author: "징기스칸", category: "리더십" },
    { id: 300, quote: "꿈꾸기를 멈추지 않는 한 영원히 젊다.", author: "새뮤얼 울만", category: "청춘" },
    { id: 301, quote: "뿌리 깊은 나무는 바람에 흔들리지 않는다.", author: "세종대왕", category: "기초" },
    { id: 302, quote: "배우고 때때로 익히면 또한 기쁘지 아니한가.", author: "공자", category: "배움" },
    { id: 303, quote: "말이 앞서지 말고 행동이 앞서라.", author: "논어", category: "실행" },
    { id: 304, quote: "인내는 모든 문을 여는 열쇠다.", author: "터키 속담", category: "인내" },
    { id: 305, quote: "마음의 평화가 가장 큰 부다.", author: "탈무드", category: "행복" },
    { id: 306, quote: "실수를 두려워하면 배울 수 없다.", author: "존 듀이", category: "성장" },
    { id: 307, quote: "작은 일에 감사할 줄 아는 사람이 큰일을 맡는다.", author: "성경", category: "감사" },
    { id: 308, quote: "자기 자신을 아는 것이 지혜의 시작이다.", author: "소크라테스", category: "지혜" },
    { id: 309, quote: "흐르는 물은 썩지 않는다.", author: "여씨춘추", category: "변화" },
    { id: 310, quote: "오늘 걷지 않으면 내일은 뛰어야 한다.", author: "카를레스 푸욜", category: "성실" },
    { id: 311, quote: "용기 없는 지혜는 열매를 맺지 못한다.", author: "그라시안", category: "용기" },
    { id: 312, quote: "칭찬은 사람을 변화시키는 가장 강력한 힘이다.", author: "카네기", category: "소통" },
    { id: 313, quote: "성공은 준비와 기회의 만남이다.", author: "세네카", category: "준비" },
    { id: 314, quote: "정직은 가장 확실한 자산이다.", author: "세르반테스", category: "정직" },
    { id: 315, quote: "하루하루를 인생의 마지막 날처럼 살아라.", author: "마르쿠스 아우렐리우스", category: "현재" },
    { id: 316, quote: "남을 비판하기 전에 자신을 먼저 돌아보라.", author: "채근담", category: "성찰" },
    { id: 317, quote: "시간은 누구도 기다려주지 않는다.", author: "영국 속담", category: "시간" },
    { id: 318, quote: "지나친 욕심은 화를 부른다.", author: "명심보감", category: "절제" },
    { id: 319, quote: "지혜로운 자는 말을 아끼고 행동으로 보여준다.", author: "노자", category: "실행" },
    { id: 320, quote: "모든 어려움 뒤에는 성장이 기다리고 있다.", author: "괴테", category: "희망" },
    { id: 321, quote: "남에게 베푼 친절은 결코 사라지지 않는다.", author: "이솝", category: "친절" },
    { id: 322, quote: "신념을 가진 한 사람은 관심만 있는 아흔아홉 명보다 강하다.", author: "존 스튜어트 밀", category: "신념" },
    { id: 323, quote: "배움을 게을리하면 마음이 거칠어진다.", author: "맹자", category: "배움" },
    { id: 324, quote: "작은 습관이 모여 위대한 운명을 만든다.", author: "오비디우스", category: "습관" },
    { id: 325, quote: "어제의 실패는 오늘의 교훈이다.", author: "처칠", category: "회복력" },
    { id: 326, quote: "자신을 낮출수록 인격은 높아진다.", author: "공자", category: "겸손" },
    { id: 327, quote: "침묵은 때로 가장 강력한 웅변이다.", author: "달라이 라마", category: "지혜" },
    { id: 328, quote: "마음이 건강해야 몸도 건강하다.", author: "유베날리스", category: "건강" },
    { id: 329, quote: "희망은 영혼의 닻이다.", author: "성경", category: "희망" },
    { id: 330, quote: "끝까지 가는 자만이 정상의 경치를 본다.", author: "괴테", category: "끈기" },
    { id: 331, quote: "남을 돕는 것은 곧 나를 돕는 것이다.", author: "벤자민 프랭클린", category: "상생" },
    { id: 332, quote: "약속은 목숨처럼 지켜야 한다.", author: "안중근", category: "신뢰" },
    { id: 333, quote: "어두운 밤일수록 별은 더욱 빛난다.", author: "도스토옙스키", category: "위로" },
    { id: 334, quote: "지혜는 나이가 아니라 경험에서 나온다.", author: "키케로", category: "지혜" },
    { id: 335, quote: "분노는 어리석음으로 시작해 후회로 끝난다.", author: "피타고라스", category: "감정" },
    { id: 336, quote: "오늘 뿌린 씨앗이 내일의 숲을 이룬다.", author: "중국 격언", category: "미래" },
    { id: 337, quote: "자신을 이기는 자가 천하를 얻는다.", author: "한비자", category: "자제" },
    { id: 338, quote: "진정한 친구는 역경 속에서 알아본다.", author: "아리스토텔레스", category: "우정" },
    { id: 339, quote: "배움은 평생 동안 마르지 않는 샘물이다.", author: "탈무드", category: "배움" },
    { id: 340, quote: "가장 소중한 순간은 바로 지금이다.", author: "레프 톨스토이", category: "현재" },
    { id: 341, quote: "성실함이야말로 인생 최고의 밑천이다.", author: "루소", category: "성실" },
    { id: 342, quote: "남을 존중해야 나도 존중받는다.", author: "율곡 이이", category: "존중" },
    { id: 343, quote: "실패를 두려워하지 않는 용기가 성공을 낳는다.", author: "포드", category: "용기" },
    { id: 344, quote: "독서는 마음의 양식이다.", author: "데카르트", category: "독서" },
    { id: 345, quote: "작은 일에 최선을 다하면 큰일도 이룬다.", author: "콜리어", category: "정성" },
    { id: 346, quote: "지혜로운 자는 남의 칭찬에 우쭐하지 않는다.", author: "채근담", category: "겸손" },
    { id: 347, quote: "시간을 낭비하는 것은 생명을 낭비하는 것이다.", author: "영국 격언", category: "시간" },
    { id: 348, quote: "진정한 행복은 내면의 평화에서 온다.", author: "스피노자", category: "행복" },
    { id: 349, quote: "모든 시작에는 설렘과 두려움이 공존한다.", author: "헤세", category: "도전" },
    { id: 350, quote: "오늘의 노력이 내일의 나를 만든다.", author: "칸트", category: "노력" },
    { id: 351, quote: "남의 장점을 보면 내 마음도 맑아진다.", author: "퇴계 이황", category: "인성" },
    { id: 352, quote: "정직한 자는 어둠 속에서도 빛난다.", author: "솔로몬", category: "정직" },
    { id: 353, quote: "변화를 두려워하면 성장은 멈춘다.", author: "드러커", category: "혁신" },
    { id: 354, quote: "고난은 사람을 단련시키는 풀무불이다.", author: "성경", category: "성장" },
    { id: 355, quote: "작은 친절이 하루를 바꾼다.", author: "카네기", category: "친절" },
    { id: 356, quote: "배움이 없는 삶은 어둠 속을 걷는 것과 같다.", author: "공자", category: "배움" },
    { id: 357, quote: "스스로 길을 찾는 자에게 문이 열린다.", author: "에머슨", category: "주체성" },
    { id: 358, quote: "지혜로운 자는 과거에서 배우고 미래를 창조한다.", author: "처칠", category: "지혜" },
    { id: 359, quote: "마음이 바르면 모든 일이 순조롭다.", author: "명심보감", category: "기본" },
    { id: 360, quote: "포기하지 않는 열정이 모든 장벽을 무너뜨린다.", author: "만델라", category: "열정" },
    { id: 361, quote: "겸손은 지혜의 어머니이다.", author: "소크라테스", category: "겸손" },
    { id: 362, quote: "시간을 소중히 여기는 자가 승리한다.", author: "프랭클린", category: "시간" },
    { id: 363, quote: "진정한 친구는 보물보다 귀하다.", author: "키케로", category: "우정" },
    { id: 364, quote: "어려울 때일수록 기본으로 돌아가라.", author: "동양 격언", category: "원칙" },
    { id: 365, quote: "자신의 한계를 규정짓지 마라.", author: "나폴레온 힐", category: "잠재력" },
    { id: 366, quote: "웃음은 마음의 치료제다.", author: "탈무드", category: "힐링" },
    { id: 367, quote: "정의로운 마음이 가장 강한 방패다.", author: "셰익스피어", category: "정의" },
    { id: 368, quote: "꿈을 향해 나아가는 발걸음은 결코 헛되지 않다.", author: "괴테", category: "꿈" },
    { id: 369, quote: "남을 배려하는 마음이 아름다운 세상을 만든다.", author: "마더 테레사", category: "배려" },
    { id: 370, quote: "오늘의 인내가 내일의 영광이 된다.", author: "플라톤", category: "인내" },
    { id: 371, quote: "지식보다 중요한 것은 그것을 쓰는 지혜다.", author: "아인슈타인", category: "지혜" },
    { id: 372, quote: "성실한 하루가 모여 빛나는 일생이 된다.", author: "세네카", category: "성실" },
    { id: 373, quote: "남의 탓을 하기 전에 자신의 행동을 돌아보라.", author: "채근담", category: "성찰" },
    { id: 374, quote: "희망은 절망 속에서 피어나는 꽃이다.", author: "빅토르 위고", category: "희망" },
    { id: 375, quote: "스스로를 신뢰하는 자만이 남의 신뢰를 얻는다.", author: "에머슨", category: "신뢰" },
    { id: 376, quote: "배움을 멈추지 않는 한 영원히 청춘이다.", author: "울만", category: "청춘" },
    { id: 377, quote: "작은 일도 정성껏 하면 위대한 결실을 맺는다.", author: "중용", category: "정성" },
    { id: 378, quote: "마음의 문을 열면 세상이 들어온다.", author: "헤세", category: "소통" },
    { id: 379, quote: "끝까지 최선을 다한 자에게 후회는 없다.", author: "이순신", category: "최선" },
    { id: 380, quote: "용기 있게 도전하는 자만이 세상을 바꾼다.", author: "잡스", category: "도전" },
    { id: 381, quote: "남을 용서할 때 내 마음이 자유로워진다.", author: "달라이 라마", category: "용서" },
    { id: 382, quote: "지혜로운 자는 말을 아끼고 귀를 기울인다.", author: "탈무드", category: "경청" },
    { id: 383, quote: "시간은 가장 공평한 자원이다.", author: "피터 드러커", category: "시간" },
    { id: 384, quote: "정직함은 어떤 상황에서도 빛을 잃지 않는다.", author: "칸트", category: "정직" },
    { id: 385, quote: "모든 역경 뒤에는 반드시 도약이 따른다.", author: "처칠", category: "역경" },
    { id: 386, quote: "감사하는 마음은 모든 미덕의 근원이다.", author: "키케로", category: "감사" },
    { id: 387, quote: "스스로 한계를 정하지 않으면 불가능은 없다.", author: "만델라", category: "잠재력" },
    { id: 388, quote: "친절은 영혼을 아름답게 가꾸는 화장품이다.", author: "톨스토이", category: "친절" },
    { id: 389, quote: "오늘 하루를 값지게 쓰는 자가 승리자다.", author: "단테", category: "현재" },
    { id: 390, quote: "변화를 수용하는 유연함이 생존의 비결이다.", author: "다윈", category: "생존" },
    { id: 391, quote: "마음의 평정은 그 무엇과도 바꿀 수 없다.", author: "아우렐리우스", category: "평정" },
    { id: 392, quote: "남의 성공을 진심으로 축하해 주어라.", author: "카네기", category: "동행" },
    { id: 393, quote: "배움은 미래를 여는 황금 열쇠다.", author: "조지 워싱턴", category: "배움" },
    { id: 394, quote: "작은 실천 하나가 거대한 비전보다 값지다.", author: "에디슨", category: "실행" },
    { id: 395, quote: "신뢰를 쌓는 데는 오랜 시간이 걸리지만 무너지는 것은 순식간이다.", author: "버핏", category: "신뢰" },
    { id: 396, quote: "자신을 다스리는 자가 가장 위대한 정복자다.", author: "플라톤", category: "자제" },
    { id: 397, quote: "어둠 속에서도 길을 잃지 않는 것은 희망의 빛 덕분이다.", author: "헬렌 켈러", category: "희망" },
    { id: 398, quote: "성실하게 살아온 날들은 결코 사라지지 않는다.", author: "괴테", category: "성실" },
    { id: 399, quote: "지혜로운 자는 고요함 속에서 진리를 찾는다.", author: "노자", category: "지혜" },
    { id: 400, quote: "내일을 꿈꾸며 오늘을 충실히 살아라.", author: "아인슈타인", category: "인생" },
    { id: 401, quote: "결과는 노력의 무게를 정확히 반영한다.", author: "아리스토텔레스", category: "노력" },
    { id: 402, quote: "깊은 강물은 소리 없이 흐른다.", author: "셰익스피어", category: "겸손" },
    { id: 403, quote: "꿈을 현실로 만드는 것은 오직 행동뿐이다.", author: "피카소", category: "실행" },
    { id: 404, quote: "신뢰는 모든 인간관계의 주춧돌이다.", author: "에머슨", category: "신뢰" },
    { id: 405, quote: "비바람을 견딘 나무만이 가장 단단한 열매를 맺는다.", author: "괴테", category: "인내" },
    { id: 406, quote: "시간을 다스리지 못하면 시간에 쫓기게 된다.", author: "세네카", category: "시간" },
    { id: 407, quote: "남을 이해하려는 노력이 곧 사랑의 시작이다.", author: "톨스토이", category: "이해" },
    { id: 408, quote: "지혜로운 사람은 실수를 통해 배우고 전진한다.", author: "처칠", category: "성장" },
    { id: 409, quote: "작은 일에 충실한 자가 큰일을 해낸다.", author: "탈무드", category: "기본" },
    { id: 410, quote: "모든 위대한 성취는 열정에서 시작되었다.", author: "헤겔", category: "열정" },
    { id: 411, quote: "남의 시선에 흔들리지 말고 내 길을 가라.", author: "단테", category: "주체성" },
    { id: 412, quote: "정직함이야말로 최고의 전략이다.", author: "프랭클린", category: "정직" },
    { id: 413, quote: "오늘의 포기는 내일의 후회가 된다.", author: "조던", category: "끈기" },
    { id: 414, quote: "배움을 멈추지 않는 마음이 가장 젊은 마음이다.", author: "울만", category: "배움" },
    { id: 415, quote: "친절한 말 한마디가 누군가의 인생을 바꿀 수 있다.", author: "카네기", category: "친절" },
    { id: 416, quote: "고난은 숨겨진 축복이다.", author: "헬렌 켈러", category: "희망" },
    { id: 417, quote: "마음의 평화를 지키는 것이 진정한 승리다.", author: "아우렐리우스", category: "평화" },
    { id: 418, quote: "성공은 준비된 자가 기회를 만났을 때 찾아온다.", author: "파스퇴르", category: "준비" },
    { id: 419, quote: "남을 용서하는 자는 가장 강한 자다.", author: "간디", category: "용서" },
    { id: 420, quote: "작은 친절도 결코 헛되지 않다.", author: "이솝", category: "친절" },
    { id: 421, quote: "시련은 사람을 더욱 단단하게 만든다.", author: "니체", category: "시련" },
    { id: 422, quote: "오늘 하루를 소중히 여기는 자가 내일을 얻는다.", author: "호라티우스", category: "현재" },
    { id: 423, quote: "생각이 깊을수록 행동은 신중해진다.", author: "공자", category: "신중함" },
    { id: 424, quote: "웃음은 가장 강력한 소통의 도구다.", author: "찰리 채플린", category: "긍정" },
    { id: 425, quote: "변화를 두려워하지 않는 자가 세상을 이끈다.", author: "빌 게이츠", category: "혁신" },
    { id: 426, quote: "감사하는 마음은 영혼을 풍요롭게 한다.", author: "키케로", category: "감사" },
    { id: 427, quote: "자신을 이기는 자가 가장 위대한 영웅이다.", author: "플라톤", category: "자제" },
    { id: 428, quote: "진정한 명예는 바른 삶에서 나온다.", author: "루소", category: "명예" },
    { id: 429, quote: "끝까지 버티는 자가 승리한다.", author: "한니발", category: "끈기" },
    { id: 430, quote: "지혜는 학교가 아닌 인생 전체에서 배운다.", author: "아인슈타인", category: "지혜" },
    { id: 431, quote: "정의로운 마음은 어떤 유혹도 이겨낸다.", author: "칸트", category: "정의" },
    { id: 432, quote: "배움은 영원히 마르지 않는 샘물이다.", author: "순자", category: "배움" },
    { id: 433, quote: "남을 배려하는 마음이 세상을 따뜻하게 한다.", author: "테레사 수녀", category: "배려" },
    { id: 434, quote: "시간은 모든 것을 치유하는 명의다.", author: "메난드로스", category: "시간" },
    { id: 435, quote: "스스로를 믿는 자에게 길은 항상 열려 있다.", author: "에머슨", category: "자신감" },
    { id: 436, quote: "작은 일에 충실한 것이 위대함의 씨앗이다.", author: "중용", category: "정성" },
    { id: 437, quote: "실패를 거듭해도 열정을 잃지 마라.", author: "처칠", category: "열정" },
    { id: 438, quote: "마음의 평정이 최고의 부귀영화다.", author: "세네카", category: "행복" },
    { id: 439, quote: "오늘의 고통은 내일의 힘이 된다.", author: "괴테", category: "희망" },
    { id: 440, quote: "남의 잘못을 들추기 전에 자신을 돌아보라.", author: "채근담", category: "성찰" },
    { id: 441, quote: "용기 있는 선택이 운명을 바꾼다.", author: "페리클레스", category: "용기" },
    { id: 442, quote: "정직함이야말로 가장 안전한 길이다.", author: "솔로몬", category: "정직" },
    { id: 443, quote: "꿈을 품고 사는 자는 늙지 않는다.", author: "울만", category: "꿈" },
    { id: 444, quote: "작은 습관이 모여 큰 차이를 만든다.", author: "오비디우스", category: "습관" },
    { id: 445, quote: "지혜로운 자는 고요함 속에서 길을 찾는다.", author: "노자", category: "지혜" },
    { id: 446, quote: "신뢰는 모든 성공의 기본 바탕이다.", author: "버핏", category: "신뢰" },
    { id: 447, quote: "포기하지 않는 마음이 기적을 부른다.", author: "만델라", category: "끈기" },
    { id: 448, quote: "친절은 누구나 이해할 수 있는 언어다.", author: "마크 트웨인", category: "친절" },
    { id: 449, quote: "스스로를 낮추는 자가 존경을 받는다.", author: "공자", category: "겸손" },
    { id: 450, quote: "오늘 하루를 마지막 날처럼 성실히 살아라.", author: "마르쿠스 아우렐리우스", category: "성실" },
    { id: 451, quote: "남의 허물을 덮어주는 것이 참된 우정이다.", author: "플루타르코스", category: "우정" },
    { id: 452, quote: "시간을 낭비하는 것은 미래를 잃는 것이다.", author: "프랭클린", category: "시간" },
    { id: 453, quote: "배움을 게을리하지 않는 자는 언제나 빛난다.", author: "맹자", category: "배움" },
    { id: 454, quote: "마음이 바르면 세상도 바르게 보인다.", author: "퇴계 이황", category: "인성" },
    { id: 455, quote: "모든 시련 뒤에는 값진 보상이 기다린다.", author: "키케로", category: "희망" },
    { id: 456, quote: "행동 없는 생각은 공허할 뿐이다.", author: "칸트", category: "실행" },
    { id: 457, quote: "자신을 이기는 자가 진정한 승리자다.", author: "부처", category: "자제" },
    { id: 458, quote: "작은 친절이 큰 행복을 가져다준다.", author: "탈무드", category: "행복" },
    { id: 459, quote: "변화를 두려워하지 않는 자만이 발전한다.", author: "잡스", category: "도전" },
    { id: 460, quote: "정직은 최고의 지혜다.", author: "토머스 제퍼슨", category: "정직" },
    { id: 461, quote: "오늘의 노력이 내일의 영광을 낳는다.", author: "세네카", category: "노력" },
    { id: 462, quote: "지혜로운 자는 말을 아끼고 실천을 앞세운다.", author: "논어", category: "실행" },
    { id: 463, quote: "희망은 영혼의 닻과 같다.", author: "히브리서", category: "희망" },
    { id: 464, quote: "남을 배려하는 마음이 진정한 품격이다.", author: "카네기", category: "품격" },
    { id: 465, quote: "끝까지 최선을 다한 자에게 실패란 없다.", author: "이순신", category: "최선" },
    { id: 466, quote: "스스로를 존중해야 남도 나를 존중한다.", author: "괴테", category: "자존감" },
    { id: 467, quote: "마음의 평온이 가장 큰 행복이다.", author: "스피노자", category: "평화" },
    { id: 468, quote: "작은 일에 성실한 자가 큰일을 맡는다.", author: "성경", category: "성실" },
    { id: 469, quote: "고난은 인간의 진가를 시험하는 무대다.", author: "셰익스피어", category: "시련" },
    { id: 470, quote: "시간을 소중히 쓰는 자가 인생을 지배한다.", author: "알랭", category: "시간" },
    { id: 471, quote: "지식보다 중요한 것은 상상력과 실천이다.", author: "아인슈타인", category: "창의성" },
    { id: 472, quote: "남의 성공을 배우려는 자세가 성공의 지름길이다.", author: "드러커", category: "성장" },
    { id: 473, quote: "진정한 용기는 두려움 속에서 전진하는 것이다.", author: "존 웨인", category: "용기" },
    { id: 474, quote: "신뢰는 한 번 깨지면 돌이키기 어렵다.", author: "쇼펜하우어", category: "신뢰" },
    { id: 475, quote: "모든 큰 성취는 작은 시작에서 출발한다.", author: "노자", category: "시작" },
    { id: 476, quote: "감사할 줄 아는 사람이 진정한 부자다.", author: "에피쿠로스", category: "감사" },
    { id: 477, quote: "자신의 약점을 인정하는 것이 강함의 비결이다.", author: "헤겔", category: "자기인식" },
    { id: 478, quote: "오늘 흘린 땀방울은 내일의 열매가 된다.", author: "탈무드", category: "노력" },
    { id: 479, quote: "지혜로운 자는 남의 말에 귀를 기울인다.", author: "플루타르코스", category: "경청" },
    { id: 480, quote: "포기하지 않는 자에게 불가능이란 없다.", author: "나폴레옹", category: "끈기" },
    { id: 481, quote: "친절은 세상을 밝히는 등불이다.", author: "마더 테레사", category: "친절" },
    { id: 482, quote: "겸손한 마음이 배움의 기초다.", author: "공자", category: "겸손" },
    { id: 483, quote: "정직한 자의 길은 언제나 곧다.", author: "솔로몬", category: "정직" },
    { id: 484, quote: "오늘 하루를 가치 있게 채워라.", author: "단테", category: "현재" },
    { id: 485, quote: "변화 속에 기회가 숨어 있다.", author: "처칠", category: "혁신" },
    { id: 486, quote: "마음의 평화가 최고의 행복이다.", author: "달라이 라마", category: "평화" },
    { id: 487, quote: "스스로를 믿는 자만이 기적을 만든다.", author: "로망 롤랑", category: "자신감" },
    { id: 488, quote: "작은 실천이 거대한 변화를 부른다.", author: "에디슨", category: "실행" },
    { id: 489, quote: "남을 용서할 때 참된 자유를 얻는다.", author: "간디", category: "용서" },
    { id: 490, quote: "시간은 다시 돌아오지 않는 소중한 보물이다.", author: "호라티우스", category: "시간" },
    { id: 491, quote: "배움을 게을리하지 마라.", author: "순자", category: "배움" },
    { id: 492, quote: "시련은 강한 의지를 낳는다.", author: "니체", category: "성장" },
    { id: 493, quote: "남을 존중하는 것이 나를 존중받는 길이다.", author: "율곡", category: "존중" },
    { id: 494, quote: "끝까지 달리는 자만이 결승선에 도달한다.", author: "괴테", category: "완성" },
    { id: 495, quote: "지혜로운 자는 고요함 속에서 힘을 기른다.", author: "노자", category: "지혜" },
    { id: 496, quote: "모든 위대한 일은 한 걸음부터 시작된다.", author: "도덕경", category: "시작" },
    { id: 497, quote: "신뢰는 인생에서 가장 값진 자산이다.", author: "버핏", category: "신뢰" },
    { id: 498, quote: "슬럼프는 자신내면의 꾀병이다.", author: "금메달리스트 이상화", category: "희망" },
    { id: 499, quote: "성실한 태도가 빛나는 미래를 연다.", author: "루소", category: "성실" },
    { id: 500, quote: "성공은 최종적인 것이 아니며, 실패는 치명적인 것이 아니다. 중요한 것은 계속할 용기다.", author: "윈스턴 처칠", category: "실행" }
];